" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

"==========================================
" Initial Plugin
"==========================================

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Colorscheme https://github.com/sainnhe/gruvbox-material
Plug 'sainnhe/gruvbox-material'

" Syntax highlight https://github.com/sheerun/vim-polyglot
Plug 'sheerun/vim-polyglot'

" Markdown https://github.com/plasticboy/vim-markdown
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'

call plug#end()


"==========================================
" General Settings
"==========================================

syntax on

set number
set history=500
set autoread
set showcmd
set showmode
set hidden

" Search
set incsearch
set hlsearch
set ignorecase
set smartcase

" Security
set modelines=0
set nomodeline

" Allow backspace in insert mode
set backspace=indent,eol,start

" Disable cursor blink
set gcr=a:blinkon0

"Always show current position
set ruler

" Tab autocomplete and ignore
set wildmode=list:longest,full
set wildignore=*.pyc
set wildignore=*.jpg,*.png,*.gif

" Never recognizes leading zero number as octal number
set nrformats-=octal

let mapleader=","

filetype plugin on
filetype indent on

set autoindent
set smartindent
set smarttab
set expandtab

" Colorscheme config, see :help gruvbox-material.txt
if has('termguicolors')
  set termguicolors
endif
set background=dark
let g:gruvbox_material_background = 'hard'
"let g:gruvbox_material_background = 'soft'
colorscheme gruvbox-material

" Markdown config
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_toc_autofit = 1

